-- CreateEnum
CREATE TYPE "LoanType" AS ENUM ('PERSONAL', 'AUTO', 'MORTGAGE', 'STUDENT', 'BUSINESS', 'CREDIT_CARD', 'MEDICAL', 'HOME_EQUITY', 'PAYDAY', 'CONSOLIDATION', 'OTHER');

-- AlterTable
ALTER TABLE "loan" ADD COLUMN     "loanType" "LoanType" NOT NULL DEFAULT 'OTHER';
